function fCurrentJulianYear = GetCurrentJulianYear()
	%
	aiCurrentGregorianDate = fix(clock);
	fCurrentJulianYear = Time.GregorianDateToJulianDate(	aiCurrentGregorianDate(1),	...
															0, 							...
															0, 							...
															0, 							...
															0, 							...
															0							);
	%
end % function

