function afCurrentJulianDate = GetCurrentJulianDate()
	%
	aiCurrentGregorianDate = fix(clock);
	afCurrentJulianDate = Time.GregorianDateToJulianDate(	aiCurrentGregorianDate(1), ...
															aiCurrentGregorianDate(2), ...
															aiCurrentGregorianDate(3), ...
															aiCurrentGregorianDate(4), ...
															aiCurrentGregorianDate(5), ...
															aiCurrentGregorianDate(6) );
	%
end %
