function fNextHour = GetNextHour( fJulianDate )
	%
	fOneHourAfterCurrentJulianDate = fJulianDate + Time.GetJulianHour;
	%
	[	iYearAfter,				...
		iMonthAfter,			...
		iDayAfter,				...
		iHourAfter,				...
		iMinutesAfter,			...
		iSecondsAfter	] = 	...
			Time.JulianDateToGregorianDate( fOneHourAfterCurrentJulianDate );
	%
	fNextHour = Time.GregorianDateToJulianDate(	iYearAfter,		...
												iMonthAfter,	...
												iDayAfter,		...
												iHourAfter,		...
												0,				...
												0				);
	%
	% DEBUG
% 	Time.JulianDateToString( fNextHour )
	%
end % function

