function iDay = GregorianDateToDayOfYear(	iYear,		...
											iMonth,		...
											iDay,		...
											iHour,		...
											iMinute,	...
											iSecond		)
	%
	fJulianDate = Time.GregorianDateToJulianDate( iYear, iMonth, iDay, iHour, iMinute, iSecond );
	%
	iDay = Time.JulianDateToDayOfYear( fJulianDate );
	%
end %
