function iNumberOfHours = NumberOfHoursInPeriod( fStartingJulianDate, fEndingJulianDate )
	%
	iNumberOfHours =									...
		(												...
			(fEndingJulianDate - fStartingJulianDate)	...
			/											...
			Time.GetJulianHour()						...
		);
	%
end % function

