function iNumberOfDays = NumberOfDaysInPeriod( fStartingJulianDate, fEndingJulianDate )
	%
	iNumberOfDays =										...
		floor											...
		(												...
			(fEndingJulianDate - fStartingJulianDate)	...
			/											...
			Time.GetJulianDay()							...
		);
	%
end %
