function fCurrentJulianMonth = GetCurrentJulianMonth()
	%
	aiCurrentGregorianDate = fix(clock);
	fCurrentJulianMonth = Time.GregorianDateToJulianDate(	aiCurrentGregorianDate(1),	...
															aiCurrentGregorianDate(2),	...
															0, 							...
															0, 							...
															0, 							...
															0							);
	%
end % function

