function fNextMidnight = GetNextMidnight( fJulianDate )
	%
	[	iYear,				...
		iMonth,				...
		iDay,				...
		iHour,				...
		iMinutes,			...
		iSeconds	] = 	...
			Time.JulianDateToGregorianDate( fJulianDate );
	%
	fNextMidnight = Time.GregorianDateToJulianDate(	iYear,			...
													iMonth,			...
													iDay,			...
													24,				...
													0,				...
													0				);
	%
end % function

