%   DateToJulianDay.m Julian day number from Gregorian date.
%
%   fJulianDay = DateToJulianDay(YEAR, MONTH, DAY) returns the Julian
%   day number of the given date (Gregorian calendar)
%
%   Start of the Julian day count is from 0 at 12 noon 1 January -4712
%   (4713 BC), Julian proleptic calendar.  Note that this day count conforms
%   with the astronomical convention starting the day at noon, in contrast
%   with the civil practice where the day starts with midnight.
%
%   Astronomers have used the Julian period to assign a unique number to
%   every day since 1 January 4713 BC.  This is the so-called Julian Day
%   (JD).  JD 0 designates the 24 hours from noon UTC on 1 January 4713 BC
%   (Julian proleptic calendar) to noon UTC on 2 January 4713 BC.
%
%   Sources:  - http://tycho.usno.navy.mil/mjd.html
%             - The Calendar FAQ (http://www.faqs.org)
%
%   Author:      Peter John Acklam
%   Time-stamp:  2002-05-24 13:30:06 +0200
%   E-mail:      pjacklam@online.no
%   URL:         http://home.online.no/~pjacklam
%
function fJulianDate = GregorianDateToJulianDate(	iYear,		...
													iMonth,		...
													iDay,		...
													iHour,		...
													iMinute,	...
													iSecond		)
	%
	a = floor((14 - iMonth)/12);
	y = iYear + 4800 - a;
	m = iMonth + 12*a - 3;
	%
	% For a date in the Gregorian calendar:
	fJulianDate =	iDay					...
				+	floor((153*m + 2)/5) 	...
				+	y*365					...
				+	floor(y/4)				...
				-	floor(y/100)			...
				+	floor(y/400)			...
				-	32045					...
				+							...
				(							...
					+ 3600 * (iHour - 12)	...
					+ 60 * iMinute			...
					+ iSecond				...
				) / 86400;
	%
end %
