function astrDates = JulianDateToString( afJulianDates )
	%
	[	aiYears,			...
		aiMonths,			...
		aiDays,				...
		aiHours,			...
		aiMinutes,			...
		aiSeconds	] = 	...
			Time.JulianDateToGregorianDate( afJulianDates );
	%
	astrDates	= cell( numel(aiYears), 1 );
	%
	for iDate = 1:numel( aiYears )
		%
		astrDates(iDate) = {sprintf('%04d:%02d:%02d-%02d:%02d:%02d',	...
									aiYears(iDate),						...
									aiMonths(iDate),					...
									aiDays(iDate),						...
									aiHours(iDate),						...
									aiMinutes(iDate),					...
									aiSeconds(iDate)					)};
		%
	end;%
	%
end % function

