function fJulianDate = UnixTimeToJulianDate( iUnixTime )
	%
	[	iYear,												...
		iMonth,												...
		iDay,												...
		iHour,												...
		iMinute,											...
		iSecond		] =										...
			datevec( datenum(1970,1,1) + iUnixTime / 86400 );
	%
	fJulianDate = Time.GregorianDateToJulianDate(	iYear,		...
													iMonth,		...
													iDay,		...
													iHour,		...
													iMinute,	...
													iSecond		);
	%
	%
end %
